### ISSUE TITLE
Statistics tab does nothing

### ISSUE THREAD

**Issue by maetthew** [d4nj1/TLPUI#48] opened 2019-02-16 21:14 UTC
None of the buttons on the statistics tab does anything for me. Clicking "Simple" nothing happens at all. Clicking "complete" I'm asked for su privileges but nothing happens after I enter the password.

Any help appreciated.

Kubuntu 18.04
KDE Plasma 5.12.7
KDE Frameworks 5.47.0
QT 5.9.5
Kernel 4.15.0-45-generic

**Comment by d4nj1** [comment] 2019-02-18 13:30
Hi, can you tell me which versio nof tlp you use?
It should be printed out in the first line when calling the following via command line:

`tlp-stat -c`

Kind regards

**Comment by maetthew** [comment] 2019-02-18 21:45
@d4nj1 TLP 1.1. Installed through apt if that matters.

**Comment by d4nj1** [comment] 2019-02-19 21:08
Hi, I will try to reproduce this.

**Comment by d4nj1** [comment] 2019-02-19 21:40
Just installed Kubuntu 18.04 in virtualbox but not able to reproduce your behaviour.
Could it be that the text in the textarea from the statistics tab has the same color as the background.
Maybe you have a theme applied that shows this wrong for GTK applications.

Could you please click into the statistics textarea and `ctrl+a` to mark all text and see if it is visible then?

Kind regards

**Comment by maetthew** [comment] 2019-02-20 23:13
Hi @d4nj1 

Hmm that's weird. The text is not white, i can see the original text in there which do not change whatever I do. Screenshot after ctrl+a: https://imgur.com/a/xjX50HD

**Comment by d4nj1** [comment] 2019-02-21 20:35
Hi @maetthew,
now I understood. So the button click does not change the content of the textarea. I'm not shure what causes the issue, but it may be a GTK problem in Kubuntu 18.04. I get a lot of deprication warnings when executing TLPUI there.
Can you tell me which KDE Theme you are using?

**Comment by maetthew** [comment] 2019-02-26 01:47
@d4nj1 Yeah sorry about the "usually" vague description but that was literally what happened, nothing :)

Okay so, apparently it works with `python3 -m tlpui` as intended. It also works when I use `tlpui`. However, it does not work when launched from application launcher (.desktop) with either `Exec=/usr/bin/tlpui` nor `Exec=/usr/bin/python3 -m tlpui`

**tlpui.desktop**
```
[Desktop Entry]
Encoding=UTF-8
Name=TLPUI
Keywords=tlp;power;
Exec=
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=battery-good-charging
Categories=Application;Utility;
StartupNotify=true```

**Comment by d4nj1** [comment] 2019-02-26 20:17
Hi @maetthew,
sorry for misinterpreting you initial issue post. I should have read it more carefully.

I tried all your provided execution examples but could not reproduce this behaviour for **.desktop** entries in a Kubuntu 18.04 VirtualBox environment.

* Did you install TLPUI via PPA like https://launchpad.net/~linuxuprising/+archive/ubuntu/apps?
* Does the **Reload** button on the _Configuration_ tab work when the **Simple** button does not?

**Comment by maetthew** [comment] 2019-03-03 01:25
Hi again @d4nj1,

I am pretty sure I installed it via PPA, but not 100%. The reload button seems to work as far as I can tell.

I should mention that I recently switched full time from Windows to Linux and have been running it solely on my machine for the past 3 months or so. I have had limited experience with Linux servers before on an on-and-off basis for maybe 15 years or so I'm not completely new to Linux but new to Linux DE's and in the mean time I've messed around a lot so it might be something specific to my configuration that I've broke. I plan on reinstalling Kubuntu (at least I think, I might go with another distro) in the coming days/~2 weeks or so and I'll try to test it again.

**Comment by maetthew** [comment] 2019-03-03 01:37
Video here for further clarification: https://streamable.com/munw6

**Comment by d4nj1** [comment] 2019-03-04 20:10
Hi,
thanks for the video. I totally believed you before. ;)
Messing around with your system can cause a lot of problems, but having one button working and the other not is strange. And why is it only having trouble when run via **.desktop**- file execution?

I just added the ability to pass stderr to stdout when tlp-stat gets executed. Could you do me the favor and download the latest master and link the **.desktop** to it? Like `Exec=/usr/bin/python3 -m /path/to/latest/master/tlpui`
Then run and click the buttons again and report back?

Thanks in advance

**Comment by maetthew** [comment] 2019-03-04 23:15
> Hi,
> thanks for the video. I totally believed you before. ;)

Hehe :)

> Messing around with your system can cause a lot of problems, but having one button working and the other not is strange. And why is it only having trouble when run via **.desktop**- file execution?
> 
Yeah it's so weird, just thought I'd mention just in case there was a hole in my knowledge somewhere :)

> I just added the ability to pass stderr to stdout when tlp-stat gets executed. Could you do me the favor and download the latest master and link the **.desktop** to it? Like `Exec=/usr/bin/python3 -m /path/to/latest/master/tlpui`
> Then run and click the buttons again and report back?
> 

So I git cloned into .tmp/ in my home folder and then tried this .desktop file:

```
#!/usr/bin/env xdg-open
[Desktop Entry]
Encoding=UTF-8
Name=TLPUI-test
Keywords=tlp;power;
Exec=/usr/bin/python3 -m /home/ma/.tmp/TLPUI
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=battery-good-charging
Categories=Application;Utility;
StartupNotify=true
```

I'm not sure about the path, the git root folder is 'TLPUI', and within that there's 'tlpui'. I've tried both TLPUI and TLPUI/tlpui and all it does is this when I try to open it:

https://streamable.com/kymhy

> Thanks in advance

**Comment by maetthew** [comment] 2019-03-07 21:24
Well I decided to do a fresh install of my system and now it's working like intended. Idk what this was, very weird.

**Comment by d4nj1** [comment] 2019-03-08 20:33
Thanks for feedback. The Exec I suggested was not quite right.
`Exec=bash -c "PYTHONPATH=/home/ma/.tmp/TLPUI /usr/bin/python3 -m tlpui"`
would have done it I think.

Anyway, if it occures again please don't hesitate to raise an issue.

**Comment by d4nj1** [comment] 2019-03-11 09:08
Closing this for now.

**Closed by d4nj1** 2019-03-11 09:08 UTC
Labels: bug
