### ISSUE TITLE
Settings not showing when clicking on "edit" in DISK_DEVICES_ID

### ISSUE THREAD

**Issue by chaotic-bruno** [d4nj1/TLPUI#44] opened 2018-12-25 01:16 UTC
After making settings for multiple disks ([tab]Disks->[section]DISK_DEVICES_ID->edit), window jumps from tab "Disks" to tab "General".

When trying to click on "edit" in Disks again nothing happens.

Console shows this:

> Traceback (most recent call last):
  File "/opt/tlpui/tlpui/ui_config_objects/gtkdisklist.py", line 30, in edit_list
    existingdisks = read_existing_disk_config()
  File "/opt/tlpui/tlpui/ui_config_objects/gtkdisklist.py", line 216, in read_existing_disk_config
    existingdiskconfig[device] = [apmlevelonac[index], apmlevelonbat[index], spindowntimeoutonac[index], spindowntimeoutonbat[index], iosched[index]]
IndexError: list index out of range

(can I provide anything else thats useful?)

**Comment by d4nj1** [comment] 2018-12-25 14:51
Hi,
thanks for reporting. I'm not able to reproduce the error right now. Seems like it occurs when more than one disk is available. I try to get another Laptop with multiple disk devices for error reproduction.
Can you provide the mounts of your disks as shown with:

> tlp-stat -d

It should be something like **/dev/sda**

Kind regards

**Comment by chaotic-bruno** [comment] 2018-12-25 16:13
Hey,

Storage devices are:
> /dev/sda:
  Model     = Samsung SSD 850 EVO 500GB               
  Firmware  = EMT02B6Q
  APM Level = none/disabled
  Status    = active/idle
  TRIM      = supported
  Scheduler = cfq
  Runtime PM: control = on, autosuspend_delay =   -1
  /dev/sdb:
  Model     = ST2000LX001-1RG174                      
  Firmware  = SDM1    
  APM Level = 128
  Status    = standby
  Scheduler = cfq
  Runtime PM: control = on, autosuspend_delay =   -1

**Comment by d4nj1** [comment] 2018-12-25 20:59
Hi,
I managed to add a mock device to reproduce the error. As I thought there was an issue when multiple devices available. A fix has just been commited. Please test against latest master and report back if you still face any errors.

**Comment by chaotic-bruno** [comment] 2018-12-26 03:50
It works now! thanks a lot.

Window jumps still to tab "General" when clicking on "OK" after editing disks. But this behavior is a minor bug.

**Comment by d4nj1** [comment] 2018-12-26 10:14
Hi,
this does not happen to me. I think your problem might be the same as reported in #39.
Could you check the TLPUI config file for content? It should be in /home/username/.config/tlpui/tlpui.cfg or in $XDG_CONFIG_HOME/tlpui/tlpui.cfg and look like this:

> [default]
> language = en_EN
> tlpconfigfile = /etc/default/tlp
> activecategorie = 7
> windowxsize = 900
> windowysize = 600

Maybee you have an old unsupported version of this file.

Did you ever run tlpui before? Could you paste your config here?

**Comment by d4nj1** [comment] 2018-12-28 12:51
Hi,
thanks for the detailed report. I will look deeper into this as this is an unexpected behaviour.
Having one **tlpui.cfg** file for root and user seems to be due to the fact that Tlpui may be run in user or root context (sudo, pkexec). I'm not shure if this can be avoided.
But the fact that the category does not switch back to the category defined in **activecategorie** is a real issue.

Trying to reproduce to find the root of the cause.

**Comment by d4nj1** [comment] 2019-01-08 22:42
Hi,
I tried hard to reproduce the category switch behaviour but I can't. I added some config file handling improvements but I do not think that this might help in your case.

Can you tell me how you run the tlpui version you have downloaded from here?
Are you using it like this?

`cd /home/lukas/Downloads/TLPUI-master && python3 -m tlpui`

**Comment by chaotic-bruno** [comment] 2019-01-15 23:34
Hey,
sorry for the late answer - next week exams start and I'm pretty busy.
Yes I start tlpui like this.
I moved the old version to "[...]/TLPUI-master_old" and downloaded the newest version with updated config file handling. Still the same error.

Maybe this behavior is related to a weird gtk bug in netrunner rolling / arch. I will test with other distros on my main pc since I have to reinstall linux on that machine anyway.

But it will take appr. 2 weeks until exams are over.
Thanks a lot for your effort despite this bug not being relevant to the core function of tlpui.

PS: you were right with two config files related to running with or without root permission

**Comment by d4nj1** [comment] 2019-01-21 20:08
Hi,
good luck with your exams. I'm more than happy when you report back whenever possible. No hurry.

Kind regards

**Comment by d4nj1** [comment] 2019-03-04 19:43
Hi @chaotic-bruno,
how did you exams go? Any news on the issue you were facing?

**Comment by d4nj1** [comment] 2019-05-15 16:39
I will close this as there was no further feedback.

**Closed by d4nj1** 2019-05-15 16:39 UTC
Labels: wontfix
